### ISSUE TITLE
Python migration

### ISSUE THREAD

**Issue by c-martinez** [TIBHannover/FAIR-R#11]
I really like the content in this lesson! I would like to teach this lesson, but my audience are more likely to be receptive to Python.

Are there any efforts already underway to migrate this lesson to Python? If not, what would be the best way to go about it?

**Comment by katrinleinweber** [comment]
Hello and thanks for the praise :-)

No, there are no efforts AFAIK. And I wouldn't recommend it, because the idea of this lesson was basically to distill `r-novice-inflammation` down to functions, their formal documentation, packaging and testing. I don't know much about Python, but [episodes 6 to 9 of `python-novice-inflammation`](https://swcarpentry.github.io/python-novice-inflammation/) seem to have that, as well as [Katy Huff's `python-testing`](https://katyhuff.github.io/python-testing/). And if those only have 80% of what you want, please don't make the same mistake as I did: going for the 100% of what I wanted (this lesson), rather than for +10% in the form of PRs to the existing lessons.

My conclusion from our workshop was, that I built by far too much lesson material myself (we didn't get through the entire `FAIR-R` lesson), instead of re-using others' lessons and sending PRs with change that I felt necessary. So, I honestly feel a bit ashamed that I diverged this fork as much as it did. It's more difficult than necessary to integrate anything back into the original.

**Comment by c-martinez** [comment]
Hi,

Ok, that makes sense, I think. The python-testing indeed looks a bit like what I am after. I would like to also include something around packaging for python, but maybe, like you say, that would be a +10% PR and not necessarily a new lesson.

Many thanks!

**Comment by katrinleinweber** [comment]
You're welcome :-)
