### ISSUE TITLE
To be explicit, when and what are instructors teaching?

### ISSUE THREAD

**Issue by lwjohnst86** [TIBHannover/FAIR-R#9]
I've looked around but can't find it. What are the exact dates that each of us are teaching and what exactly are we each covering (what files in this repo are we each going over)?

Just so I can plan and prepare accordingly! :smile:

**Comment by katrinleinweber** [comment]
That info is on the first "Agenda" slide of each slide deck in the GDrive ;-) Because several instructors didn't want to have the schedule link to the slides before the workshop, I'm not posting the GDrive link here.

R with you and me will mostly be on Wednesday afternoon and Thursday. _Maybe_ we can squeeze in the function episode on Tuesday already, but Python has prio on Tue & Wed.

Looking back, that separation of info wasn't ideal in the end. Maybe a `dev` branch would have been better. I think that's what I'd try next time: collect every such piece of info in the schedule, just not right in front of the learners.

**Comment by lwjohnst86** [comment]
Ah, so we will cover all of the FAIR-R material from beginning to end over the course of Wednesday afternoon to Thursday? That seems fair (ha, fair :stuck_out_tongue:)

I saw the agenda on the slides, I just didn't know which exact material we would would be going over and when (aka, which files or sections in this repo).

**Comment by katrinleinweber** [comment]
Yeah, none of us is sure how the timing will play out. There are some "FAIR-R/0..." links in the slides, which are a rough hint when to switch from presentation to live-coding.

But yes, generally this entire lesson will be taught. Let's hope it's not a case of sunken cost fallacy 😬

I suggest we both prepare all episodes, but if time gets constrained, feel free to cherry-pick half of them and let me know your choice ;-)

**Comment by lwjohnst86** [comment]
Ok, no worries. I am pretty familiar with most carpentry and R related teaching material, so should be ok whatever we end up teaching :)
